// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhqpcsuontjvceryevbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocXBjc3VvbnRqdmNlcnlldmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Njg1NjEsImV4cCI6MjA2NzE0NDU2MX0.vN8uCZXz7HrPxgpWXf8dJqW6tugrebs1Npvtb248MOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});